linters:
  enable:
      - errcheck
          - govet
              - staticcheck
                  - ineffassign
                      - gosimple
                          - unused

                          linters-settings:
                            govet:
                                enable-all: true

                                issues:
                                  exclude-use-default: false
                                    max-issues-per-linter: 0
                                      max-same-issues: 0
